language: android

android:
  components:
    - tools
    - platform-tools

jdk:
  - oraclejdk8

before_script:
  - yes | sdkmanager --licenses

before_install:
  - pip install --user codecov

install: true

script: ./gradlew clean build

after_success:
  - codecov

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2